### ISSUE TITLE
Broadcast issues additional key to terminals

### ISSUE THREAD

**Issue by Isgleas** [gnome-terminator/terminator#78] opened 2020-05-14 08:51 UTC
When grouping terminals and broadcasting on them, the keys typed on the focused one are keyed twice on the other terminals.

Lets say, if I type `ls` on the main terminal, I get `llss` on the others on the group. The same happens when setting broadcast to all,

Terminator v 1.91 on Opensuse Leap 15.1

![image](https://user-images.githubusercontent.com/3003504/81913676-942dff00-95d0-11ea-8952-bac1d582bc26.png)

**Comment by mattrose** [comment] 2020-05-14 15:42
I believe this has been fixed in master.  Can you try:
```
git clone https://github.com/gnome-terminator/terminator
cd terminator
./terminator -u
``` 
to try it out?

**Comment by Isgleas** [comment] 2020-05-14 16:09
I see the same behavior

![image](https://user-images.githubusercontent.com/3003504/81958148-d6296600-960d-11ea-92c1-d23b6e5563d0.png)

**Comment by lazyfrosch** [comment] 2020-05-14 19:50
confirmed in my setup

**Comment by mattrose** [comment] 2020-05-14 20:37
weird, I'm not seeing that either on fedora or my mac, and my mac terminator install is as quirky as hell :)

**Comment by mattrose** [comment] 2020-05-14 20:39
![image](https://user-images.githubusercontent.com/65013/81983434-6614e300-9601-11ea-81ab-e8f3f9a85438.png)

**Comment by Isgleas** [comment] 2020-06-03 09:47
I have found this issue happens if I'm on KDE Xorg, it does not show neither on KDE Wayland, Gnome Wayland nor Gnome Xorg. I have tried modifying some of the keyboard related env variables but none of them seem to affect
![image](https://user-images.githubusercontent.com/3003504/83621751-60bb1080-a58f-11ea-8a6f-8f15fb884084.png)
![image](https://user-images.githubusercontent.com/3003504/83621931-9e1f9e00-a58f-11ea-942c-25c33693f4e0.png)

**Comment by Isgleas** [comment] 2020-06-03 09:47
Closed it by mistake

**Comment by mattrose** [comment] 2020-06-03 18:51
Well, this was an adventure. It turns out that it wasn't the environment variable that changed, but actually the internals of the python psutil module, which meant that we weren't actually detecting whether or not ibus was running, and consequently never setting the proper ibus environment variable.

Can anyone who has encountered this bug please check out the PR and test it?

**Comment by Isgleas** [comment] 2020-06-03 19:00
Setting the environment variable seems to fix the broadcast issue, but some shortcuts, not all, start working funny, like triggering an emoji list menu

![image](https://user-images.githubusercontent.com/3003504/83677903-29735080-a5dd-11ea-8b60-7845b9f80a38.png)


![image](https://user-images.githubusercontent.com/3003504/83677455-7d316a00-a5dc-11ea-8f53-42a4a671cfbb.png)

**Comment by Isgleas** [comment] 2020-06-03 19:12
PR114 seems to work, great!
![image](https://user-images.githubusercontent.com/3003504/83678882-bf5bab00-a5de-11ea-9fd1-f28f6dc26490.png)

**Comment by mattrose** [comment] 2020-06-03 19:12
Great, I'll pull this in soon.  Thanks for testing it out so quickly.

**Comment by ozzdemir** [comment] 2020-12-20 09:33
It still happens to me with commit 6c56f32eeb4306371842bc1aba17b1b677ec0352
Tried deleting environment variable by adding `del os.environ['GTK_IM_MODULE']` to terminator before main called. It works, but then I cant launch a layout from Terminator Layout Launcher.
Using Ubuntu 18.04, and installed from source with the mentioned commit.

**Comment by mattrose** [comment] 2020-12-20 16:00
I'm going to re-open this to check this out.

**Comment by ozzdemir** [comment] 2020-12-26 19:57
When I tried to start layout from terminal, observed that it was giving keyError since GTK_IM_MODULE env var is already deleted (probably), when I handled it in a try except block, now I can start from layout. Final form of the addition (Just before `if __name__ == '__main__':`) I made is as follows:
```
try:
    del os.environ['GTK_IM_MODULE']
except Exception as e:
    print(e)
```
I did not open a merge request since I am not sure if this is the best way to handle it, but if anyone wants a quick solution can use it.

**Comment by mattrose** [comment] 2020-12-30 21:28
I reverted #36, can you retest this and close it if it's fixed again?

**Comment by ozzdemir** [comment] 2020-12-31 09:14
Checked issue78 branch, and there was no such problem.

**Comment by mattrose** [comment] 2021-01-16 18:22
Did you update master from upstream?

**Comment by ozzdemir** [comment] 2021-01-16 19:14
Yes, I did at the time and tried again just now. Still persists.
`terminator --version` reports `terminator 2.1.0`. If there is a call that returns the commit hash or so, I can also share it.

**Comment by ozzdemir** [comment] 2021-01-16 19:52
It seems the bug introduced by 736e88aa4606f8a2ea4a8d82fc63e6a9d34e51db. I did find it by sectioning commits and testing for the problem.

**Comment by mattrose** [comment] 2021-01-16 19:56
Hmm, can you see if the ibus fix referenced in that commit is in your version of ibus?

**Comment by ozzdemir** [comment] 2021-01-16 20:21
How can I check it? Seems my IBus version is 1.5.17.

**Comment by mattrose** [comment] 2021-01-21 18:32
That should have the fix in it, I'll see if I can reproduce this in an ubuntu 18.04 vm soon

**Comment by Joshua-Snapp** [comment] 2021-01-28 04:26
I also have this problem when broadcasting to multiple panes. The current workaround that seems to work is to set `DBUS_SESSION_BUS_ADDRESS=''` and start terminator with the `-u` option described in the [DBus](https://gnome-terminator.readthedocs.io/en/latest/advancedusage.html#dbus) section of the Terminator documentation.

I added the following alias to my `~/.bashrc` to make this workaround more convenient to run.
```
alias terminator="DBUS_SESSION_BUS_ADDRESS='' terminator -u"
```

I'm running the following:
- Fedora 32
- ibus.x86_64 1.5.22-7.fc32
- terminator.noarch 2.1.0-1.fc32
- gtk3.x86_64 3.24.23-1.fc32

Enabled Terminator Plugins:
- LaunchpadBugURLHandler
- LaunchpadCodeURLHandler
- APTURLHandler
- TerminatorThemes
- TerminatorSearch

**Comment by xbello** [comment] 2021-02-05 09:03
I've been able to make it work creating the executable file `~/bin/terminator` (assuming your ~/bin has preference) as:

    export DBUS_SESSION_BUS_ADDRESS=$(dbus-launch)
    /usr/bin/terminator

I did this because the terminator.desktop launcher doesn't seem to use the alias from the .bashrc

**Comment by mattrose** [comment] 2021-06-22 17:47
I think this workaround is best if anyone is still hitting this issue. Anytime I try and fix this in code it breaks more critical functionality.

**Closed by mattrose** 2021-06-22 17:47 UTC
Labels: question

**Comment by yuki** [comment] 2021-11-23 16:09
Same issue on Terminator 2.1.0-2 on Debian bookworm (actually "testing").
The workaround

> export DBUS_SESSION_BUS_ADDRESS=$(dbus-launch)
> /usr/bin/terminator


is working

**Comment by yurenchen000** [comment] 2022-04-18 09:57
ubuntu20.04, fcitx google-pinyin.

the situation I encountered:

## env other

// this no effecit
```sh
QT4_IM_MODULE= QT_IM_MODULE= DBUS_SESSION_BUS_ADDRESS= /usr/bin/terminator -u
```

<br>

## env GTK_IM_MODULE

// this fixed, but will lose fcitx input
```sh
GTK_IM_MODULE=  /usr/bin/terminator -u
```

<br>

// this fixed, but also lose fcitx input
```diff
--- a/usr/bin/terminator
+++ b/usr/bin/terminator
@@ -23,6 +23,12 @@ import sys
 import os
 import psutil
 import pwd
+
+try:
+    del os.environ['GTK_IM_MODULE']
+except Exception as e:
+    print(e)
+
 try:
     ORIGCWD = os.getcwd()
 except OSError:
```

<br>

so, the current workaround principle is disable input method ?
may be this is a temporary workaround ?

**Comment by JKomoroski** [comment] 2023-04-05 14:24
For those using terminator 2.1.1 and are launching terminator from a `.desktop` shortcut (i.e Fedora). I was able to work around this issue edit the `Exec` argument to include an empty Dbus address.

Copy the system terminator desktop file to my local application shortcut directory. For example on my system:
```
cp /usr/share/applications/terminator.desktop ~/.local/share/applications 
```
Open the copied result file in the local applications folder and edit the `Exec=terminator` to: 
```
Exec=env DBUS_SESSION_BUS_ADDRESS= terminator -u
```

**Comment by Arondight** [comment] 2023-04-06 08:09
Damn you can't delete the GTK_IM_MODULE environment variable, tons of users need to use it! [THIS CODE SUCKS!](https://github.com/ozzdemir/terminator/commit/1e8940039a75b5a6fb32e59b4a2130da4777065f)

**Comment by mattrose** [comment] 2023-04-06 13:55
agreed, that's why I pulled it in the latest release.

**Comment by bmullan** [comment] 2023-12-02 15:58
On Ubuntu 22.04.3 LTS

My Terminator got updated sometime recently to a newer version that exhibited the duplicate character issue when
Broadcasting between multiple Terminator "window" sessions.

*I finally fixed it on my system by editing*:

> **$ sudo nano /usr/share/applications/terminator.desktop** 

Change the line "**Exec=terminator**" to:
> ***Exec=env DBUS_SESSION_BUS_ADDRESS= terminator -u***

Testing: 

Start Terminator,  split the window so you have 2 Terminator sessions.
In one of those **select Broadcast All**

It now works again on my Ubuntu system w/no character duplication!

**Comment by awsms** [comment] 2023-12-26 20:42
still having this issue on 2.1.3

**Comment by xbello** [comment] 2023-12-27 09:55
> On Ubuntu 22.04.3 LTS
> 
> My Terminator got updated sometime recently to a newer version that exhibited the duplicate character issue when Broadcasting between multiple Terminator "window" sessions.
> 
> _I finally fixed it on my system by editing_:
> 
> > **$ sudo nano /usr/share/applications/terminator.desktop**

This kind of changes might be overwritten in the next upgrade. It could be in a couple of months or in a couple of years. And then you won't remember how did you fix it.

You should edit instead your user `terminator.desktop` that usually is at `$HOME.local/share/applications/`. If it doesn't exist, create one by copying the file from the system.

**Comment by alohl669** [comment] 2024-09-06 07:22
Ubuntun 20.04
using xorg(does not happen on wayland)
terminador 2.1.3

terminator still working wrong

![image](https://github.com/user-attachments/assets/a52ea44b-4cd4-4734-8822-13bc85101243)

**Comment by eamathw** [comment] 2024-10-17 19:47
Ubuntu 22.04.5 LTS
Terminator 2.1.1-1

This problem only started when I switched from Wayland to Xorg(to fix Zoom screen sharing issue at work). The solution I've been using is:
` GTK_IM_MODULE= terminator `

**Comment by sudoix** [comment] 2024-11-03 15:54
Still having this issue:
terminator 2.1.3
Ubuntu 24.04

**Comment by bmullan** [comment] 2024-11-03 16:58
This fixed it for me.
Make backup of this file then..

*Edit*:

*> $ sudo nano /usr/share/applications/terminator.desktop*

Change the line "*Exec=terminator*" to:

*Exec=env DBUS_SESSION_BUS_ADDRESS= terminator -u*

See if that fixes it for you

**Comment by mattrose** [comment] 2024-11-03 17:14
This disables all dbus functionality and *does* work, but there's a *much* easier way than editing the desktop file.   You can just disable the dbus server in the preferences here https://gnome-terminator.readthedocs.io/en/latest/preferences.html

> *Edit*: *> $ sudo nano /usr/share/applications/terminator.desktop* Change the line "*Exec=terminator*" to: *Exec=env DBUS_SESSION_BUS_ADDRESS= terminator -u*

**Comment by bmullan** [comment] 2024-11-04 01:31
@mattrose 
Thanks for that link!
