### ISSUE TITLE
Upgraded 21.10 to 22.04, input is doubled on broadcast windows

### ISSUE THREAD

**Issue by kellyschoenhofen** [gnome-terminator/terminator#596] opened 2022-05-03 14:41 UTC
**Describe the bug**
Upgraded 21.10 to 22.04, input is doubled on broadcast windows.

**To Reproduce**
Open Terminator, split horizontally, broadcast all, press a key. One shows up in the foreground window, two shows up in the split window. 

**Expected behavior**
The same number of characters are broadcast as entered. 

**Desktop:**
 - Ubuntu
 - 22.04
 - X11

**Comment by mattrose** [comment] 2022-05-04 00:53
What version of terminator are you running?  

if you run under `terminator -u` does that fix the problem?

**Comment by kellyschoenhofen** [comment] 2022-05-04 14:24
My apologies, I should have included the version. 

```
$ sudo apt-cache policy terminator
terminator:
  Installed: 2.1.1-1
  Candidate: 2.1.1-1
  Version table:
 *** 2.1.1-1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe i386 Packages
        100 /var/lib/dpkg/status
```
`terminator -u` didn't change the behavior, the non-infocus broadcast windows have the doubled chars.

**Comment by mattrose** [comment] 2022-05-08 13:44
Ugh, can you check out master and see it if has the same problem?  I think we've done some work on that since the last release.

**Comment by kellyschoenhofen** [comment] 2022-05-09 21:03
OK, I tried, I think I did what you asked. 
I couldn't tell if I was _really_ using terminator from the repo, so I uninstalled terminator (e.g. sudo apt remove terminator) and I'm 100% sure when I did 'python3 terminator' it was running the one I cloned from github. I did have to put back a few dependencies though, 
```
sudo apt install python3-psutil python3-configobj gir1.2-keybinder-3.0 libkeybinder-3.0-0
```
and yes, non-primary broadcasted windows had doubled chars. 

Then I wanted to build it and see if the same thing happened, I believe I also needed to install intltool and gettext so successfully build it, but it built and I replaced the terminator and remotinator from the build/scripts-3.10/ folder, and the same issue still persisted, doubled chars. 

This was a 21.10 desktop upgraded to 22.04, I'll spin up a 22.04 vm fresh from the iso and see if this occurs.

**Comment by mattrose** [comment] 2022-05-09 22:15
OK, there are a few things we can try to get this working.  It's conflicting with ibus-daemon for some reason, and we keep trying to work around it, and it seems to keep breaking in new and wonderful ways.

**Comment by ros-financial-com** [comment] 2022-05-13 10:21
I'd just like to add that I experience the same behaviour on ArchLinux 5.17.6-arch1-1 with terminator 2.1.1-3 in gnome-shell 1:42.1-1. I hope this might be helpful.

**Comment by mattrose** [comment] 2022-05-27 16:04
Doing some research[1], it may have to do with the odd way we set application id for subsequent windows here: https://github.com/gnome-terminator/terminator/blob/d33c145ba806dab65696c7c9d3fcba46a85a4f69/terminatorlib/ipc.py#L30

[1] https://discourse.gnome.org/t/svg-icon-in-desktop-file-no-longer-shows-in-dock-when-app-opens-gear-icon-instead/9647

**Comment by dreamonhigh** [comment] 2022-06-10 05:43
same issue on Ubuntu 22.04
I can read my passphrase in cleartext on different windows. with double characters.
Terminator is not useable anymore :(

**Comment by mattrose** [comment] 2022-06-10 12:10
I've tried to install a VM with Ubuntu 22.04 with not much success, if anyone can go through the troubleshooting steps in #78 and #504, and report the results, that would help resolve this much quicker.

**Comment by Ajk4** [comment] 2022-06-23 16:57
Leaving info for others.

I tried everything posted online on Ubuntu 22.04 and nothing works.

What finally worked for me was disabling Wayland like described in this article https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop

**Comment by kellyschoenhofen** [comment] 2022-06-24 20:03
OK, I tried a few things. Switching to gnome/x11 how the prior comment linked to did not change the doubled input behavior.
Trying what was in #78 and #504, 

```
export IBUS_NO_SNOOPER_APPS=python3 
```
Did not change doubled behavior

But, 
```
export DBUS_SESSION_BUS_ADDRESS=$(dbus-launch)
# technically "fixed" the issue, it overwrote the prior:
DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1911838151/bus"
# to this:
DBUS_SESSION_BUS_ADDRESS="DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-fxgffHu2tm,guid=5b5807194ad75ceca08669a462b61759
```
Which now resulted in this output when I launched terminator:
```
$ terminator 
Unable to connect to DBUS Server, proceeding as standalone
```
but doubled behavior stopped/was fixed.

**Comment by kellyschoenhofen** [comment] 2022-06-24 20:24
OK - that export dbus_session seemed obviously malformed, so poking around, it seems on 22.04 `export $(dbus-launch)` is the correct command to set it. Doing that resulted in a manual terminator launch that:

1. didn't throw a warning/error that it was unable to connect to DBUS Server, 
2. and fixed the doubled input on broadcast issue

Setting it with just `export $(dbus-launch)` also updated the pid value correctly, e.g. 
```
$ export
declare -x DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-fAFPL65H0a,guid=a5fa200a99c760c8beb5a22c62b61ca0"
declare -x DBUS_SESSION_BUS_PID="19967"
```

**Comment by mattrose** [comment] 2022-06-25 17:33
Has anyone opened a bug with Ubuntu about this?  It seems that Ubuntu is the only distro that is having these problems, and  I think it's something to do with their weird mix of Gnome 41 and 42 and their extensions.

**Comment by mattrose** [comment] 2022-06-27 01:34
I finally got an ubuntu 22.04 desktop and am unable to reproduce this 
![Screenshot from 2022-06-26 21-26-05](https://user-images.githubusercontent.com/65013/175844079-0a1428e2-923c-48b6-8f4e-6789f2052734.png)

**Comment by mattrose** [comment] 2022-06-27 01:42
After some consideration, I'm going to close this bug now, as I can't figure out what to do next.  Please re-open if you can find a way for me to reproduce this

**Closed by mattrose** 2022-06-27 01:42 UTC
Labels: question

**Comment by dreamonhigh** [comment] 2022-06-27 14:50
Sorry, I've forgotten.
I tried once more. start terminator. make "tile horizontal". make another terminator open(move it to the right), and do again "tile horizontal".
type some text in upper left tiled window .. look in other windows .. output is twice shown in 3 other tiled terminator instance.

I did not tried in a new installation. If you still can not reproduce I will make a new installation and try again.

![Terminator](https://user-images.githubusercontent.com/46345061/175969155-165ff165-9f1d-41d9-aa6c-8bf21043e063.png)

One more thing. I downloaded like you told and started it in git clone... the upper 2 windows are from ubuntu 22.04 apt install terminator, and lower both are from git verion.

Hope this helps.

**Comment by dreamonhigh** [comment] 2022-06-27 18:43
Ok, installed now 22.04 in Virutalbox. The problem is not there. Im confused. In real system it happens everytime I starte 2 terminator windows. 
I will go asking in some #ubuntu irc if they can reproduce this issue.

**Comment by dreamonhigh** [comment] 2022-06-27 19:02
maybe there are old configs, that conflict after upgrading to 22.04?
I purged terminator and removed ./config/terminator .. maybe there is more to delete?

**Comment by mattrose** [comment] 2022-06-27 19:23
There is a very small chance that there is a config in /etc/xdg/ or in a directory in the XDG_CONFIG_DIRS array.  More likely that there is still a terminator window running under the old config. Make sure that there are no terminator sessions running (using `ps auxw | grep terminator` or something similar) before restarting.  Sometimes terminator sessions can hang around and will re-use the old config unless you stop ALL of the instances.

**Comment by dreamonhigh** [comment] 2022-06-27 19:49
Thats it. Ok, there was no /etc/xdg config. but you were right, there was still a terminator process running. I removed .config/terminator and killed this process. started again. AND.. IT WORKS LIKE IT SHOULD. I removed config, so I cannot compare anymore. maybe I have a backup that I made a month ago. I you like I would dig in there.
Im lucky to have terminator back again. ;)

**Comment by sailing0505** [comment] 2022-08-19 09:35
> I'm going to close this bug now, as I can't figure out what to do next. Please re-open i

This workaround works on my ubuntu 22.04. I was troubled for this problem for few days. Thank you.

**Comment by RockLobstah271** [comment] 2022-09-07 08:40
This bug occurred to me in WSL2. I don't know if this is relevant but my workaround was to switch off broadcasting in top left corner. Then behavior returns to normal.

**Comment by gouzhuang** [comment] 2022-10-01 07:52
I can reproduce it easily with a fresh install of Ubuntu 22.04. The key is to use Xorg instead of Wayland. There is no problem in Wayland, but once I switch to Xorg, the problem shows up.

**Comment by yurenchen000** [comment] 2022-10-01 11:19
I guess it's about input methods (at lease my ubuntu was),
 I killed ibus (maybe also fcitx) to avoid it

**Comment by chenjiayi8** [comment] 2023-03-31 10:18
> I guess it's about input methods (at lease my ubuntu was), I killed ibus (maybe also fcitx) to avoid it

This is the only solution works for me.

**Comment by kimba74** [comment] 2023-04-18 19:10
> > I guess it's about input methods (at lease my ubuntu was), I killed ibus (maybe also fcitx) to avoid it
> 
> This is the only solution works for me.

Same for me. Double characters show up only under X11 and are fixed by killing ibus.

**Comment by letsgologan** [comment] 2023-07-29 08:38
I'm using ibus for input method, is there any chance to still keep ibus running and solve this issue? Thank you.

**Comment by yurenchen000** [comment] 2023-07-29 15:43
> I'm using ibus for input method, is there any chance to still keep ibus running and solve this issue? Thank you.

@letsgologan 
I'm on ubuntu22 too, 
just share a little experience

## for fcitx 
//this will disable fcitx in terminater
> GTK_IM_MODULE=  /usr/bin/terminator -u
https://github.com/gnome-terminator/terminator/issues/78#issuecomment-1101277387

## for ibus
//ibus can work, but only broadcast eng input
> IBUS_NO_SNOOPER_APPS=python3 terminator
https://github.com/gnome-terminator/terminator/issues/504#issuecomment-915619502

**Comment by letsgologan** [comment] 2023-07-29 16:06
Hi, thank you for the suggestion, i end up backup the /usr/bin/terminator into  /usr/bin/terminator.back
and create a script called  /usr/bin/terminator like this and set execution permission for it:

#!/bin/bash
sh -c "DBUS_SESSION_BUS_ADDRESS='' /usr/bin/terminator.back"

So far it been working as expected for me.
My os and version info:
OS: Ubuntu 22.04
Terminator version: 2.1.3

On my work PC, I had the same issue but probably in a older version of Terminator.
I've been able to fix it using the answer in this:
https://askubuntu.com/questions/1189243/why-is-terminator-sending-double-characters-to-terminals-that-arent-selected-in  

But on Ubuntu 22 i can not find this file /usr/share/terminator/terminator anymore.
So far so good things been working as expected. Thank you

**Comment by mattrose** [comment] 2023-08-02 17:16
O  no I'm as e    Wwx[zxh I don't think that'll hold a play a conversation out hereow m trains are going hard grams are going no x]()> OK - that export dbus_session seemed obviously sxru hi [xeu Oh god yeah I don't knows is not coming back to the road  Xavier we x C]()malformed, so poking around, it seems on 22.04 `export $(dbus-launch)` is the correct command to set it. Doing that resulted in a manual terminator launch that:
#A new > [ C scum  D]()
>  dhccuwc wxxxxxqxqcxqcdwd  do[]()
> 
> 1. didn't throw a warning/error that it  qwnn one was wsss ox I eeesqssssaarrcu yay  Jen uciuiuxi I'm c I  was a I scared dadx sqqss  was unable to connect to DBUS Server, 
> 
> 2. and fixed the doubled input on broadcast issue
> 
> 
> 
> Setting it with just `export $(dbus-launch)` also updated the pid value correctly, e.g. 
> 
> ```
> 
> $ export
> 
> declare -x DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-fAFPL65H0a,guid=a5fa200a99c760c8beb5a22c62b61ca0"
> 
> declare -x DBUS_SESSION_BUS_PID="19967"
> 
> ```
> 
>

**Comment by pedrofilhojp** [comment] 2023-09-15 01:28
I fix my terminator closing the ibus

`ibus exit`

![image](https://github.com/gnome-terminator/terminator/assets/54863086/a03ccf76-af20-498f-b444-355155c5c42a)

**Comment by abacao** [comment] 2023-10-14 16:02
I'm facing the same issue.
Tested all options without success.

When primary is 1 char, 2nd or 3rd windows is double char.

Running:
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

```
$ terminator -v
terminator 2.1.1
```

https://github.com/gnome-terminator/terminator/issues/596#issuecomment-1116839614
Does not fix the problem.

DBUS and IBUS env
```
$ env | grep DBUS       
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
$ env | grep IBUS       
IBUS_DISABLE_SNOOPER=1
```

After `export DBUS_SESSION_BUS_ADDRESS=$(dbus-launch)`

```
$ env | grep DBUS                               
DBUS_SESSION_BUS_ADDRESS=DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-w7zo81jCgK,guid=f0115be7895589a799c9b14d652abb05
DBUS_SESSION_BUS_PID=1609509
DBUS_SESSION_BUS_WINDOWID=100663297
```

Still having the double char issue


@mattrose or @kellyschoenhofen

Can you guys please reopen this?

**Comment by gakutasu** [comment] 2024-03-27 09:05
@abacao 
The following worked on ubuntu20.04
```
sudo mv /usr/bin/terminator /usr/bin/terminator.SAVE
cat <<TERMINATOR > /tmp/terminator
#!/bin/bash
sh -c "DBUS_SESSION_BUS_ADDRESS='' /usr/share/terminator/terminator"
TERMINATOR
chmod 755 /tmp/terminator
sudo mv /tmp/terminator /usr/bin
```
