### ISSUE TITLE
[Bug][Fedora 36 KDE][terminator v2.1.1] "broadcast group" sends each terminal input/keystroke depending on the group's members count to everyone in the group

### ISSUE THREAD

**Issue by VProfirov** [gnome-terminator/terminator#704] opened 2023-01-23 09:58 UTC
As mentioned above, case:
1 tab split into 4 windows; 3 grouped in a group "SomeName" --> broadcast_group --> hi ==> hhhiii to everyone in the group (all 3 grouped windows)

Here is terminator's global config data:
[global_config]
  geometry_hinting = True
  use_custom_url_handler = True
  custom_url_handler = SomeBrowser
  inactive_color_offset = 1.0
  enabled_plugins = ActivityWatch, InactivityWatch, CommandNotify, CustomCommandsMenu, Logger, MavenPluginURLHandler, TerminalShot, TestPlugin, LaunchpadBugURLHandler, LaunchpadCodeURLHandler, APTURLHandler
  suppress_multiple_term_dialog = True
  always_split_with_profile = True
  title_use_system_font = False
  title_font = Source Code Pro Bold 13
  case_sensitive = False
  invert_search = True
  
  Terminator version 2.1.1 installed on Fedora 36 KDE.
  
  P.S. This was not the case some terminator versions back.

**Comment by mattrose** [comment] 2023-01-23 14:05
This is actually usually caused by IBus mis-behaviour.  Should be fixed by #674 but you may still have some IBus plugins with bugs in them.

**Closed by mattrose** 2023-01-23 14:05 UTC
