### ISSUE TITLE
[2.1.2] Foreground processes started in new window close immediately

### ISSUE THREAD

**Issue by jusw85** [gnome-terminator/terminator#673] opened 2022-11-10 19:24 UTC
[2.1.1]

```
## Opens in new window, window is persistent
$ terminator --execute transmission-daemon --foreground
```

https://user-images.githubusercontent.com/3406652/201187002-b83452df-fac8-4c07-9e27-eeb907b3c232.mp4

[2.1.2]

```
## Window either closes immediately or isn't even created. The command is running in the background.
$ terminator --execute transmission-daemon --foreground
```

https://user-images.githubusercontent.com/3406652/201187025-e6a5dd45-9875-4c3e-9c5f-b4399b8cbe15.mp4

**Comment by mattrose** [comment] 2022-11-18 21:12
Duplicate of #660, should be fixed in master now.

**Closed by mattrose** 2022-11-18 21:12 UTC
