### ISSUE TITLE
Tab focus change causes white-out of console

### ISSUE THREAD

**Issue by avsdev-cw** [gnome-terminator/terminator#383] opened 2021-02-17 12:33 UTC
**Describe the bug**
When terminator is out of focus with tabs active, the console area is white'd out.

**To Reproduce**
Create a new tab in terminator, move the window or change focus to another window. Removing the tabs returns behaviour to normal.

**Expected behavior**
Transparency of console area remains, terminator should behave as it does when tabs are not in use

**Screenshots**
![image](https://user-images.githubusercontent.com/25663960/108204790-247b1080-711c-11eb-912c-692e5d95940e.png)

**Desktop (please complete the following information):**
Debian 11 (Bullseye) [modified BunsenLabs flavor]
Terminator 2.1.0
Openbox 3.6.1 / lightdm 1.26.0

**Comment by mattrose** [comment] 2021-02-17 12:36
dupe of #372 Sorry about that.  There's some workarounds in there and I'm going to fix it soon

**Closed** 2021-02-17 12:36 UTC

**Comment by avsdev-cw** [comment] 2021-02-17 12:38
Ah apologies on the dupe, didn't find that one on my searches. Hit across another bug report but that had been closed and was in the current release so didn't link it. Thanks for the quick response.
