### ISSUE TITLE
Terminator doesn't update until I switch windows 

### ISSUE THREAD

**Issue by levu42** [gnome-terminator/terminator#299] opened 2020-11-21 15:32 UTC
I have a strange bug that's somewhat reproducible (happens around twice a minute by just using terminator): I type something and in the middle of me typing terminator doesn't update the UI anymore until I force it to be redrawn (e.g. by switching to the browser and back to terminator).

This mostly happens with vim being open but also occasionally without vim.

Could you assist me in getting useful debugging data about what's going on?

I use 1.92 on arch linux (x64), my shell is zsh 5.8 and vim 8.2.

**Comment by blue112** [comment] 2020-11-21 20:33
I have reproduced this on a brand new archlinux, with a fresh terminator from the repository.

**Comment by blue112** [comment] 2020-11-21 21:03
FYI it seems related to : https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3369

**Comment by mattrose** [comment] 2020-11-21 21:20
That looks about right to me.  There's even a gitlab user complaining of the same thing with terminator, as well as a bunch of other applications.  The common demonominator, as far as I can see, is GTK or Gnome, not terminator.  It really looks like Gtk.draw() calls are getting blocked until something unblocks them.  Given that this just started happening in the past few weeks or months, and the 1.92 code is well over 6 months old now, I'm really thinking that it's something else in the stack that's causing this.  

This issue and #284 seem to be the same thing.
 
@blue112 thanks for digging up that gnome issue, I'll keep an eye on it.

**Comment by blue112** [comment] 2020-11-21 21:21
A workaround for now is:
* Run terminator in fullscreen (F11), to be confirmed
* Have an always-updating-window somewhere visible, like glxgears.

**Comment by mattrose** [comment] 2020-11-21 21:23
@blue112 can you confirm that either of these fixes the issue?  If so, it's time to bring back xeyes :smiley:

**Comment by blue112** [comment] 2020-11-21 21:25
glxgears definitely fixes the issue, if at least some pixels of the glxgears window is visible.
I'm currently running on fullscreen and can't reproduce the issue, either in Terminator or SublimeText (which faces exactly the same issue).

**Comment by mattrose** [comment] 2020-11-21 21:27
Oh perfect, that pretty much confirms it's that issue.  Thanks again for digging that up

**Comment by jchillerup** [comment] 2020-11-23 09:51
The description of the problem matches my problem 100%. Sounds right about xeyes ;) 

Let me know if I can provide any helpful info.

**Comment by mattrose** [comment] 2020-11-23 13:34
This is actually a gnome-shell bug, apparently.  The team there is the one you want to work with in https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3369

**Comment by mattrose** [comment] 2020-11-23 13:35
I'm going to close this as there's nothing in the Terminator code I can fix to fix this issue.

**Closed by mattrose** 2020-11-23 13:35 UTC
