### ISSUE TITLE
Feature request: show bold text in bright colors (option)

### ISSUE THREAD

**Issue by uffejakobsen** [gnome-terminator/terminator#122] opened 2020-06-10 16:10 UTC
Feature request: show bold text in bright colors (option)

Basically a clone of the coloring checkbox option that both xfce-terminal and gnome-terminal has

PS: thanks for kicking life into this project again :-)

**Comment by mattrose** [comment] 2020-06-10 23:59
Duplicate of #38 and fixed in master thanks to @JakubVanek #39

**Closed by mattrose** 2020-06-10 23:59 UTC
