### ISSUE TITLE
terminal.py: AttributeError: 'bytes' object has no attribute 'encode'. Did you mean: 'decode'?

### ISSUE THREAD

**Issue by daniel-awake** [gnome-terminator/terminator#743] opened 2023-04-18 18:58 UTC
Not sure if this is a duplicate, but I'm opening it in case I (or anyone else) finds time to look at it. It doesn't seem to disturb anything AFAICT, so priority is low.

**Describe the bug**
After starting terminator as a background process (e.g. `terminator &` in `bash`), at unknown times, we see a stack trace:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/terminatorlib/terminal.py", line 1264, in on_drag_data_received
    term.feed(txt.encode())
  File "/usr/lib/python3.11/site-packages/terminatorlib/terminal.py", line 1697, in feed
    self.vte.feed_child(text.encode())
                        ^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'encode'. Did you mean: 'decode'?
```
**To Reproduce**
I don't know.

**Expected behavior**
Ideally, no AttributeError raised or stack trace shown (but not by catching and silencing the error :sweat_smile: .

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu
 - Version 22.04
 - Display Technology: Wayland
kernel uname: Linux daniel 5.19.0-32-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
terminator package version: 2.1.1-1 from Ubuntu universe/misc

**Additional context**

**Comment by mattrose** [comment] 2023-04-19 02:22
dupe of #727 fixed with #728 but not released yet (as of 2.1.3)

**Closed by mattrose** 2023-04-19 02:22 UTC
