### ISSUE TITLE
Unable to launch terminator

### ISSUE THREAD

**Issue by sujay1844** [gnome-terminator/terminator#346] opened 2020-12-31 06:13 UTC
> Please try moving the terminator config out of the way to see if that solves the
> problem.  If it does, and you still want to open the bug, then please attach the
> config file to the 
>  issue.

I don't understand what this means. Do I just delete the config.py??

**Describe the bug**
Terminator doesn't launch. (as simple as that)
When I run terminator from another terminal emulator, the following text shows up.
```Traceback (most recent call last):
  File "/usr/bin/terminator", line 48, in <module>
    import terminatorlib.optionparse
  File "/usr/lib/python3.9/site-packages/terminatorlib/optionparse.py", line 24, in <module>
    from . import config
  File "/usr/lib/python3.9/site-packages/terminatorlib/config.py", line 76, in <module>
    from validate import Validator
ModuleNotFoundError: No module named 'validate'
```

**Desktop (please complete the following information):**
```
System:
  Kernel: 5.9.16-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0 
  Desktop: GNOME 3.38.2 Distro: Manjaro Linux 
Machine:
  Type: Laptop System: Acer product: Swift SF314-42 v: V1.08 
  serial: <filter> 
  Mobo: RO model: Kona_RN v: V1.08 serial: <filter> UEFI: Insyde v: 1.08 
  date: 10/14/2020 
Battery:
  ID-1: BAT1 charge: 30.5 Wh condition: 39.9/47.9 Wh (83%) 
  model: Murata AP18C4K status: Discharging 
CPU:
  Info: 6-Core model: AMD Ryzen 5 4500U with Radeon Graphics bits: 64 
  type: MCP arch: Zen 2 rev: 1 L2 cache: 3 MiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 28453 
  Speed: 1406 MHz min/max: 1400/2375 MHz boost: enabled Core speeds (MHz): 
  1: 1406 2: 1855 3: 1388 4: 1428 5: 1851 6: 1918 
Graphics:
  Device-1: AMD Renoir vendor: Acer Incorporated ALI driver: amdgpu 
  v: kernel bus ID: 03:00.0 
  Device-2: Quanta HD User Facing type: USB driver: uvcvideo bus ID: 1-3:2 
  Display: x11 server: X.org 1.20.10 driver: amdgpu 
  resolution: <missing: xdpyinfo> 
  OpenGL: renderer: AMD RENOIR (DRM 3.39.0 5.9.16-1-MANJARO LLVM 11.0.0) 
  v: 4.6 Mesa 20.3.1 direct render: Yes 
Audio:
  Device-1: AMD vendor: Acer Incorporated ALI driver: snd_hda_intel 
  v: kernel bus ID: 03:00.1 
  Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor 
  vendor: Acer Incorporated ALI driver: snd_rn_pci_acp3x v: kernel 
  bus ID: 03:00.5 
  Device-3: AMD Family 17h HD Audio vendor: Acer Incorporated ALI 
  driver: snd_hda_intel v: kernel bus ID: 03:00.6 
  Sound Server: ALSA v: k5.9.16-1-MANJARO 
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel bus ID: 01:00.0 
  IF: wlp1s0 state: up mac: <filter> 
Drives:
  Local Storage: total: 476.94 GiB used: 104.24 GiB (21.9%) 
  ID-1: /dev/nvme0n1 vendor: SK Hynix model: HFM512GDJTNI-82A0A 
  size: 476.94 GiB temp: 34.9 C 
Partition:
  ID-1: / size: 169.01 GiB used: 104.24 GiB (61.7%) fs: ext4 
  dev: /dev/nvme0n1p6 
  ID-2: /boot/efi size: 511 MiB used: 352 KiB (0.1%) fs: vfat 
  dev: /dev/nvme0n1p4 
Swap:
  ID-1: swap-1 type: partition size: 15.87 GiB used: 2 MiB (0.0%) 
  dev: /dev/nvme0n1p5 
Sensors:
  System Temperatures: cpu: 45.9 C mobo: N/A gpu: amdgpu temp: 44.0 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 296 Uptime: 43m Memory: 7.21 GiB used: 4.56 GiB (63.2%) 
  Init: systemd Compilers: gcc: 10.2.0 clang: 11.0.0 Packages: 1728 
  Shell: Zsh v: 5.8 inxi: 3.2.01
```

**Comment by njZhuMin** [comment] 2020-12-31 07:28
As mentioned here, Manjaro 20.2 release introduced python 3.9 and may break python apps: https://forum.manjaro.org/t/unstable-update-2020-12-02-breakage-expected-python-3-9-nvidia-driver-simplification-kde-git/40829.

Got the same problem here. Just relax and wait for a rebuild for python 3.9. That's it.

**Comment by sujay1844** [comment] 2020-12-31 08:05
damn it!! if I knew this was gonna happen, I wouldn't have updated to 20.2 itself. I just did that today and a bunch of python stuff are breaking since then.

**Comment by mattrose** [comment] 2020-12-31 16:50
You just need to update python-configobj, this is a duplicate of #324 and #325 has some more details

**Closed by mattrose** 2020-12-31 16:50 UTC
