### ISSUE TITLE
Feature Suggestion: Splitted screen shells based on parent

### ISSUE THREAD

**Issue by ChaoticEvilDM** [gnome-terminator/terminator#230] opened 2020-10-08 13:57 UTC
I am currently using zsh alongside bash, since I prefer to handle certain tasks in each. Terminator invokes a new shell, based on the users default shell when splitting a window, rather than the shell originally used in the parent window. It would be a great improvement to have the shell based on the parent - as an option e.G.

**Comment by mattrose** [comment] 2020-10-08 15:08
Closing this as a duplicate of #229

**Closed by mattrose** 2020-10-08 15:08 UTC
