### ISSUE TITLE
Hide window in waybar

### ISSUE THREAD

**Issue by mshzsh** [gnome-terminator/terminator#633] opened 2022-08-17 14:49 UTC
hide window not working on wayland

**Comment by maximstewart** [comment] 2022-08-17 19:10
It's a known issue with the way that the hide API works. (Best my understanding goes it's X11 API reliant and Wayland doesn't have a similar call.)

**Comment by mattrose** [comment] 2022-08-18 11:11
dupe of #427

**Closed by mattrose** 2022-08-18 11:11 UTC
