### ISSUE TITLE
Setting PS1 does not update window title

### ISSUE THREAD

**Issue by hemberger** [gnome-terminator/terminator#76] opened 2020-05-13 17:02 UTC
I have the following in my `~/.bashrc`:
```
export PS1="\[\e]0;\w\a\]\w \$ "
```
With this setting, the Terminator "titlebar" and tab title get updated when I change directory, but the window title does not.

![image](https://user-images.githubusercontent.com/846186/81841271-09310400-94ff-11ea-8000-36bb9ecbd375.png)

![image](https://user-images.githubusercontent.com/846186/81841307-177f2000-94ff-11ea-8b82-545d1ef1dbc0.png)

This occurs even with a single tab with no tiling:
![image](https://user-images.githubusercontent.com/846186/81841365-2e257700-94ff-11ea-9af1-4638a06c3589.png)

This also occurs if I turn off the Terminator "titlebar":
![image](https://user-images.githubusercontent.com/846186/81841621-95dbc200-94ff-11ea-97c8-771c15bc52ef.png)

As you can see here, it is not even getting its initial value from `PS1`:
![image](https://user-images.githubusercontent.com/846186/81842343-b7897900-9500-11ea-97e3-47fb4d68fa5e.png)

However, this is working correctly with GNOME Terminal (both the tab and window titles get updated when I change directory):
![image](https://user-images.githubusercontent.com/846186/81841648-9d9b6680-94ff-11ea-82f2-8313ab1bb3c2.png)

I am running Terminator v1.91 and GNOME Terminal v3.36.1.1. Please let me know if any further information about my system is required to nail down this issue. Thank you!

**Comment by lazyfrosch** [comment] 2020-05-13 19:25
Welcome @hemberger

**Comment by mattrose** [comment] 2020-05-14 15:40
I can't reproduce this at all.  I don't think we've touched any of the title changing mechanisms recently, but can you try checking out the latest copy of the repo and try running it there:
```
git clone https://github.com/gnome-terminator/terminator
cd terminator
./terminator -u
```
should get you running the latest master.

It won't fix your problem, but it should tell us that we may have fixed it in the latest version.

What os/version are you running?  If you get back to us with that, I can try reproducing it in a VM.

**Comment by lazyfrosch** [comment] 2020-05-14 15:42
As said, I have the same problem, but haven't tested if it may be Wayland related. Currently I'm on Xorg.

Investigation pending

**Comment by hemberger** [comment] 2020-05-14 17:22
Tested with latest master and the issue persists. I'm running stock Ubuntu 20.04.

**Comment by xvybihal** [comment] 2020-10-02 07:10
I have tracked it down in my case. It's a configuration problem. When i cleared my ~/.config/terminator/config, the bad behavior was gone! So I did setup my terminator again to the state I like it and it works fine. It is kind of obvious now, why it was happening:

```
[layouts]
  [[default]]
    [[[child0]]]
      fullscreen = False
      last_active_term = 91b720de-71e6-4ac4-b269-218b4c16b776
      last_active_window = True
      maximised = False
      order = 0
      parent = ""
      position = 2125:133
      size = 1019, 641
      title = jv@jv:~
      type = Window
    [[[terminal1]]]
      order = 0
      parent = child0
      profile = jvubuntu
      type = Terminal
      uuid = 91b720de-71e6-4ac4-b269-218b4c16b776
```
The title was enforced by my configuration!

I am not sure at what point it was set up, but I don't remember setting such odd thing by myself (manualy), so I guess it was set at some point when I was experimenting with different terminator versions, different layouts and using same config file.


I am now at terminator 1.92.207.ge9eb89ef and after fixing the config, the issue is gone. Hope that helps someone struggling with same thing :)

**Comment by lazyfrosch** [comment] 2021-01-03 19:32
Same in my case, not sure why parts of the state here come into the configuration. Problem will be that this setting is not visible in the config UI...

**Comment by mattrose** [comment] 2021-01-03 22:18
Can we close this then?

**Comment by hemberger** [comment] 2021-01-04 05:40
I don't mind if you close it, as there is a workaround to fix it (thanks for the tip, by the way!). I _think_ that the `title` was saved in the configuration when I clicked "Save" in Preferences -> Layouts. Maybe it's worth reconsidering if this is the desired behavior?

**Closed** 2021-01-04 06:25 UTC
Labels: invalid

**Comment by ankostis** [comment] 2021-04-15 22:48
I confirm @hemberger, this bug is caused without the user's approval, when saving layouts.
