### ISSUE TITLE
System wide defaults

### ISSUE THREAD

**Issue by baryluk** [gnome-terminator/terminator#782] opened 2023-06-25 21:32 UTC
Hi,

I am using Terminator for over a decade, and love it.

Currently at terminator 2.1.2-2 on Debian.

The issue is, I use livecds very frequently, so every time I boot, I loose settings.

For example I always do change following two settings:

- Scrollback: 1000000 (1 million lines), instead of 500
- Disable F1 (help) and F10 (menu accelerator) keybindings, so they are properly forwarded to apps running in terminal instead. (I leave F11 and F12 bound usually)

So changing this every day, is annoying. Especially if you already executed the command, but history was too short, so you need to change settings, and do a rerun.

However, I can modify the livecd to change some defaults.

As far as I can see this is currently hardcoded in `/usr/lib/python3/dist-packages/terminatorlib/config.py` on my system, and I would prefer to avoid patching this file, as future updates might break it.

I also do not want to set user-specific config, because it is not something I can easily do (i.e. there might be multiple users, user home directory might not exist yet, etc).

So I would like to change some defaults.

`terminator_config` manpage and source code suggests there is no way to do this.

Any way to do this?

My suggestion, if `/etc/terminator/config` exists (I would prefer `/etc/terminator_config` actually), should be read, and any settings there should be merged with default from source code, then user config read. Any differences should be saved in user config (`~/.config/terminator/config`). Even better, maybe move hardcoded defaults to `/usr/share/terminator/config` / `/usr/local/share/terminator/config`), then read / merge order will be:

- `/usr/share/terminator/config`
- `/usr/local/share/terminator/config`
- `/etc/terminator/config`
- `/usr/local/etc/terminator/config`
- `${XDG_CONFIG_HOME:-${HOME}/.config}/terminator/config`

**Comment by mattrose** [comment] 2023-06-25 22:56
There's a variable XDG_CONFIG_DIRS which allows you to store system-wide config files that terminator started following as of 2.1.0 or so.  You should be able to put a config file in `/etc/xdg/terminator/config` that will do what you want. 

Dupe of #308

**Closed by mattrose** 2023-06-25 22:56 UTC

**Comment by baryluk** [comment] 2023-06-25 23:09
Thank you, unfortunately this feature is broken.

```
user@debian:~$ cat /etc/xdg/terminator/config
[global_config]
[keybindings]
[profiles]
  [[default]]
    scrollback_lines = 1000000


user@debian:~$ terminator 
Unable to open ‘/etc/xdg/terminator/config’ for reading and/or writting.
([Errno 13] Permission denied: '/etc/xdg/terminator/config')
```


This is because code is trying to open that file for writing.

**Comment by baryluk** [comment] 2023-06-25 23:13
Actually, it does look to work, the error message is a just bit confusing.

**Comment by baryluk** [comment] 2023-06-25 23:24
Also it might be worth documenting in `terminator_config` manual page.
