### ISSUE TITLE
feature request: Implement line spacing as a configuration option

### ISSUE THREAD

**Issue by oekelly** [gnome-terminator/terminator#542] opened 2021-11-24 23:12 UTC
Hi,

In line with this Stack Exchange question: https://unix.stackexchange.com/questions/327869/how-to-change-the-line-spacing-in-terminator

And related to this issue which was closed due to lack of response from the opener: https://github.com/gnome-terminator/terminator/issues/179

Is it possible to add a "line spacing" configuration option to terminator, now that it is supported in VTE 0.52? This is a useful feature in Gnome Terminal and KDE Konsole, and without it some taller font styles appear to cramped/tight.

Thanks!

**Comment by mattrose** [comment] 2021-11-24 23:18
It's in Preferences, under Global.  Look for Line Height.  You need 2.1.0 or later for this. Duplicate of #111

**Closed by mattrose** 2021-11-24 23:18 UTC

**Comment by oekelly** [comment] 2021-11-24 23:22
My apologies - it seems Ubuntu 20.04.3 is too far behind to make use of this. Thanks for the speedy response.

**Comment by mattrose** [comment] 2021-11-24 23:23
Use my PPA to get 2.1.1 for 20.04.3 https://launchpad.net/~mattrose/+archive/ubuntu/terminator

**Comment by oekelly** [comment] 2021-11-25 00:47
Amazing, thankyou!

**Comment by FernandoBasso** [comment] 2022-02-16 09:18
@OliverKellyATech Check I think this is related to https://github.com/gnome-terminator/terminator/pull/552. It is implemented.

**Comment by alaymari** [comment] 2023-04-25 11:49
I found this change quite helpful. A request: Please update the `terminator_config` manpage to show this option. I am currently using the 2.1.3 version in debian.
