### ISSUE TITLE
Start maximised no longer works in Gnome 44.1

### ISSUE THREAD

**Issue by qftlzxfz** [gnome-terminator/terminator#758] opened 2023-05-08 08:40 UTC
Since the upgrade from Gnome 43.5 to Gnome 44.1 Terminator no longer starts maximised.

Actually, there is an animation from maximised to normal window size when Terminator starts. So it looks as if it starts maximised, but immediately goes to normal window size. Perhaps it is a different interaction with Gnome 44.1.

This happens for both the global setting "Window state: Maximised" as well as using the -m or -M command-line option. They all show the same behaviour.

Other applications do not have this new problem and keep starting maximised.

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Archlinux
 - Display Technology: X11
 - Gnome 44.1
 - Linux 6.3.1-arch1-1

**Comment by justinnichols** [comment] 2023-08-03 00:18
I can confirm, this also occurs exactly as described for me.  I am on Manjaro on X11 with Gnome 44.3 and Linux kernel 6.1.41-1-MANJARO.

**Comment by justinnichols** [comment] 2023-08-05 01:59
I do wonder if [this issue](https://gitlab.gnome.org/GNOME/mutter/-/issues/2579) is causing this.  I do not know which version of mutter it would be fixed in (I'm guessing a currently unreleased 44.4 because I still experience this issue on 44.3 of gnome-shell and mutter, and mutter 44.3 shows a build date of July 6, and the fix for the issue shows July 21).

Another commenter on that ticket did say this:

```
These application do have this problem: Terminator, Visual Studio Code, Gimp, Inkscape, Rhythmbox.

Terminator has a command-line option to start maximised (-m and -M). When I use that I see an animation from maximised to normal window and then it stays as a normal (not maximised) window. The log shows:
```
So I'm inclined to believe it's related and I'm hopeful once we get an updated mutter, it'll be fixed.

**Comment by justinnichols** [comment] 2023-08-05 02:24
My hand may get slapped, but [I asked](https://gitlab.gnome.org/GNOME/mutter/-/issues/2579#note_1807201) if it would be back-ported to the gnome-44 branch prior to the release of 44.4 (which the tarballs are due tomorrow, so I'm guessing it won't get there in time).  If they don't backport to gnome-44, then we're looking at another six weeks.

Granted this isn't a critical issue, just an annoying regression from mutter :)

**Comment by mattrose** [comment] 2023-08-09 02:22
@justinnichols Thanks for tracking this down.  I'll see if I can find a way to test this, but I'm pretty sure you're right.  I'll keep this issue open until we can confirm it.

**Comment by justinnichols** [comment] 2024-05-07 20:08
Just an FYI, this was fixed with https://gitlab.gnome.org/GNOME/mutter/-/issues/2579 and is now back again with https://gitlab.gnome.org/GNOME/mutter/-/issues/3385

Hopefully the Gnome Mutter crew will be able to put this to bed completely.  I suspect this issue can effectively be closed given that issue 3385 for Mutter ideally should solve it once it's fully tested and pushed out at some point (hopefully they won't wait until Gnome/Mutter 47 to do so).

**Comment by mattrose** [comment] 2024-05-30 02:46
Closing this as it's not a terminator issue and there's nothing I can do to fix it.

**Closed by mattrose** 2024-05-30 02:46 UTC
