### ISSUE TITLE
Won't open in latest Manjaro ARM

### ISSUE THREAD

**Issue by rDybing** [gnome-terminator/terminator#354] opened 2021-01-03 22:24 UTC
Since most recent update to Manjaro ARM, Terminator won't open.

OS: Manjaro ARM Linux aarch64 
Host: Pine64 Pinebook Pro 
Kernel: 5.10.2-1-MANJARO-ARM 

Error message from when trying to open Terminator from Manjaros included konsole terminal:

```
(terminator:1562): Gtk-WARNING **: 23:17:16.139: Locale not supported by C library.
        Using the fallback 'C' locale.

(terminator:1562): Gtk-WARNING **: 23:17:16.155: Theme parsing error: gtk.css:2:33: Failed to import: Error opening file /home/**redacted**/.config/gtk-3.0/window_decorations.css: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/terminator", line 48, in <module>
    import terminatorlib.optionparse
  File "/usr/lib/python3.9/site-packages/terminatorlib/optionparse.py", line 24, in <module>
    from . import config
  File "/usr/lib/python3.9/site-packages/terminatorlib/config.py", line 76, in <module>
    from validate import Validator
ModuleNotFoundError: No module named 'validate'
```

**Comment by mattrose** [comment] 2021-01-03 22:26
Manjaro has a broken python library.  duplicate of #324

**Closed** 2021-01-03 22:28 UTC
