### ISSUE TITLE
Remove spaces between tabs

### ISSUE THREAD

**Issue by pkropachev** [gnome-terminator/terminator#331] opened 2020-12-24 18:05 UTC
Hi!

I'm using Ubuntu 20.04 and Terminator 1.91. In Ubuntu 20.04, there are spaces between tabs and borders of the main window.

![scr1](https://user-images.githubusercontent.com/34160907/103102121-9eff4680-462b-11eb-9c9c-d0e55d3c1c53.png)

Could you please advise if there is some way to remove these spaces?

I don't see such problem in Ubuntu 18.04.

![scr2](https://user-images.githubusercontent.com/34160907/103102138-af172600-462b-11eb-8df4-99964b164429.png)

 - OS or Linux Distribution: Ubuntu
 - Version: 20.04

**Comment by JAugusto42** [comment] 2020-12-27 16:49
Hi, @pkropachev did you try this in the latest version?

**Comment by pkropachev** [comment] 2020-12-29 09:41
Hi!
Yep, checked with version `terminator 2.0.1`, but see the same.

**Comment by mylk** [comment] 2020-12-29 10:17
Hey, @JAugusto42!

I'm in Arch Linux and I have the same issue. I have the window borders disabled, but they showed up after upgrading to v2.0.1.

**Comment by mattrose** [comment] 2020-12-29 15:44
@JAugusto42 are you not seeing this on your desktop.  I definitely see it on my mac, but it's a little wonky.  I'll go downstairs and check it out in the inspector on my linux box when I get a chance.

**Comment by Brambleberry4** [comment] 2020-12-29 22:42
Hey @pkropachev 
I'm using the version 2.0.1 and the problem does not occur in my Gnome 3.38.2 in Fedora 33. I also tried it on my Kali version (latest) with an Xfce 4.16.0. I hope that helps to find the problem.

**Comment by JAugusto42** [comment] 2020-12-29 23:22
@mattrose not occur with me, maybe its  the theme.....

**Comment by mylk** [comment] 2020-12-30 10:57
This is how it looks to me on Arch Linux with i3-wm:

![mylk_terminator](https://user-images.githubusercontent.com/6269827/103346649-890adf00-4a8c-11eb-86f7-e6971f3a0897.png)

Note the thickness of the vertical border between the terminals, which used to look the same as the horizontal.

```
$ terminator -v
terminator 2.0.1
```

I have the window borders and titlebar disabled.

Thank you for your time and I hope I can be of any help.

**Comment by Brambleberry4** [comment] 2020-12-30 11:01
@mylk Was this also the case in earlier versions or did it came with 2.0.1?

**Comment by mylk** [comment] 2020-12-30 11:13
Hey @Brambleberry4.

The border looked great on 1.92 and changed as soon as I upgraded to 2.0.1.

I never had the 2.0 but went straight to 2.0.1, if it gives any clue.

This is the package manager log entry (`/var/log/pacman.log`):

```
[2020-12-23T17:38:26+0200] [ALPM] upgraded terminator (1.92-3 -> 2.0.1-1)
```

**Comment by Brambleberry4** [comment] 2020-12-30 11:28
@mylk I am a new contributor, so I am not the most experienced one. When the problem does not occure before than something changed in the last updates. If I look in the release notes of 2.0.1 the change that makes the most sense to me is the fix of #225 (Multi tab breaks transparent background) so maybe something broke in the fix of this problem. At least that would be my first idea.

**Comment by Brambleberry4** [comment] 2020-12-30 12:12
could you go back to version 2.0 and look if the problem still occur? @mylk

**Comment by mylk** [comment] 2020-12-30 13:42
@Brambleberry4, yes thats a good idea!

I cloned the repo and checked out to the last 3 tags (including 1.92) and all have the same issue.

Any chances the update to 2.0.1 to modify any setting file that could also affect the other versions I tested too?

Otherwise, its really possible that another package did the blunder. I'm gonna rollback any package updates that may seem suspicious and send an update.

Thanks for your time!

**Comment by Brambleberry4** [comment] 2020-12-30 13:58
@pkropachev I looked in the virtual machine and indeed in Ubuntu this case occurs. @mylk I think your problem is not the tab tiling. Is it possible that the white stripe in the middle comes from the activated scroll bar? deactivate it and let me know if that solves the problem because by default the scroll bar can be seen.

**Comment by mylk** [comment] 2020-12-30 14:15
@Brambleberry4, thought it has to be the same with @pkropachev because it happened at the same time, but, yes it may be another case.

So, I won't make the current issue a mess, but i'll make a comment if I found what causes my case.

Unfortunately, I've always had the scrollbars disabled, so it has to be something else.

**Comment by Brambleberry4** [comment] 2020-12-30 14:17
Okay @mylk but please let me know when you found out

**Comment by mylk** [comment] 2020-12-30 14:39
I downgraded a few packages I thought may be related but it didn't work out.

Thanks for now and I'll let you know if I find a solution in the future.

**Comment by mattrose** [comment] 2020-12-30 15:10
@mylk, this is actually a different issue than the one that is initially complained about.  And I'm pretty sure this is caused by #193. If you update to current master, you'll probably notice the horizontal separator is also changed from #247.

This is pretty much by design, as GTK stopped support for allowing you to specify the handle width on paned separators, and the default separator width didn't allow you to select the first column of the terminal window, meaning it was a real pain to copy and paste from a multi-pane window.

**Comment by mylk** [comment] 2020-12-30 16:06
@mattrose, thanks for clearing it up!

**Comment by mattrose** [comment] 2020-12-30 17:37
So, on the original problem, (spacing between tabs) this is definitely a GTK change, not a Terminator change.  We leave this setting alone.

So, as a workaround you can add the following to `~/.config/gtk-3.0/gtk.css`
```
notebook tab {
	margin-left: 0px;
	margin-right: 0px;
}
```
and that will remove the spacing between the tabs.

I'm going to look into this further, because I should be able to set it as a property for those tabs specifically

**Comment by mattrose** [comment] 2020-12-30 19:19
Just looked at gnome-terminal, and it has the same spacing between tabs, and given we take our UI cues from gnome-terminal, I think I may just leave it as is.   I don't want to make Terminator too much of a special snowflake where styling is concerned.  If anyone can come up with a good way of integrating the styling I may look at it, but I'm tempted to just close this.

**Comment by pkropachev** [comment] 2021-01-08 17:55
Hi @Brambleberry4!
Exactly, this behaviour observes on Ubuntu 20.04.

Hi @mattrose!
Thanks for suggestion! It looks much better with `margin`.

![scr3](https://user-images.githubusercontent.com/34160907/104047948-8c703a00-51f3-11eb-8cf5-395ac3b40b8b.png)

**Comment by mattrose** [comment] 2021-01-08 18:17
All right, closing this then

**Closed by mattrose** 2021-01-08 18:17 UTC
