### ISSUE TITLE
Last split in tab greyed out

### ISSUE THREAD

**Issue by 4kp3ntest** [gnome-terminator/terminator#402] opened 2021-03-11 21:03 UTC
Hi - I found an issue with the most recent terminator version 2.1.0 used in debian distros.

If more than one tab is open the last created split in every tab will be greyed out if not focused.

![Unbenannt](https://user-images.githubusercontent.com/19542827/110853967-8dd1e780-82b4-11eb-83f4-3906670da6f4.PNG)

The two options that cause the behaviour if combined are:

    show_titlebar = False
    scrollbar_position = hidden

Attached is a minimalistic config
[tconfig.txt](https://github.com/gnome-terminator/terminator/files/6125932/tconfig.txt)

Some ideas how to fix it?

**Comment by mattrose** [comment] 2021-03-11 21:46
Duplicate of #372 

If you can run master, that'll fix it.  I'll try to have a point update released soon, it's about time

**Closed by mattrose** 2021-03-11 21:47 UTC
