### ISSUE TITLE
Terminator turns white when using tabs

### ISSUE THREAD

**Issue by rdagerfall** [gnome-terminator/terminator#391] opened 2021-02-19 14:39 UTC
**Describe the bug**
Terminator turns white when using tabs since latest update in Fedora 33

**To Reproduce**
1. Open terminator then open a new tab
2. Switch to any other window on your desktop (for example a Chrome browser) and have terminator side by side (see screenshot)
3. Terminator now turns white. When you switch back and use terminator, it's normal again

Please note that when NOT using tabs, everything looks normal side by side.

**Expected behavior**
Switch to any window on your desktop and terminator should be normal when visible at the same time

**Screenshots**
![Screenshot from 2021-02-19 15-12-48](https://user-images.githubusercontent.com/70325457/108516695-d5bdaa00-72c6-11eb-98af-1e8d9ce6d2cc.png)

**Desktop**
 - Linux Distribution: Fedora 33
 - Terminator: 2.1.0

**Comment by mattrose** [comment] 2021-02-19 19:57
dupe of #372

**Closed by mattrose** 2021-02-19 19:57 UTC
