### ISSUE TITLE
Pasting on tab title bar closes tab.

### ISSUE THREAD

**Issue by mood-indigo** [gnome-terminator/terminator#789] opened 2023-07-12 02:59 UTC
I am referring to the tab's title bar, not the title bar with the trio-colored grouping menu.

I copy text from one tab and paste them in another tab on a frequent basis.  But when I switch to the other tab, oftentimes I paste the text on the tab's title bar instead of the tab's background.  This closes the tab. 

I consider this an issue because I lost a lot of information that is present in the output of the commands that I had been running in that tab.

Yes, there is a workaround: I just have to be careful where I paste.  But mistakes happen.  This can be prevented.  I don't understand why the tab's title bar behaves this way.

**Comment by vssdeo** [comment] 2023-08-06 13:59
Hi @mood-indigo somehow I am not able to reproduce it so a few questions

1. does it happen every time
2. does it happen with all text or certain type and certain length
3. version of terminator you are using

**Comment by mattrose** [comment] 2023-08-23 23:30
Closing for non-response.  Please re-open if this is still an issue.

**Closed by mattrose** 2023-08-23 23:30 UTC
