### ISSUE TITLE
Broadcasting terminals duplicates keys in other terminals (Fedora 38 edition)

### ISSUE THREAD

**Issue by rmarting** [gnome-terminator/terminator#771] opened 2023-06-08 13:51 UTC
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can

**Describe the bug**

This is an issue to track how to fix the same issue already reported in the following issues, but without a clear answer how to fix it in a Fedora 38 workstation.

#78 
#504 
#719 

**To Reproduce**

Open a terminator, create two windows, broadcast to all, and type characters in one of them

**Expected behavior**

**Screenshots**

![image](https://github.com/gnome-terminator/terminator/assets/8723668/f65ae78a-32ca-4575-8925-d1231fa65f19)

**Desktop (please complete the following information):**
 - OS or Linux Distribution: [e.g. FreeBSD or Ubuntu]
 - Version [e.g. 20.04]
 - Display Technology: Wayland or X11

Environment

```shell
on 🎩 ❯ uname -a
Linux redhat 6.3.5-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 30 15:44:17 UTC 2023 x86_64 GNU/Linux
on 🎩 ❯ cat /etc/redhat-release 
Fedora release 38 (Thirty Eight)
on 🎩 ❯ terminator -v
terminator 2.1.3
```

Config file:

```shell
on 🎩 ❯ cat ~/.config/terminator/config 
[global_config]
[keybindings]
[profiles]
  [[default]]
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]
```

**Additional context**

**Comment by mattrose** [comment] 2023-06-09 00:26
This is not a bug in Terminator.  This is a known bug with certain ibus keyboards.   You don't need to be using the keyboard to have it double the characters, just have a buggy keyboard enabled and have ibus running.

The easy solution to this is to kill ibus.

If you absolutely need ibus, you need to go through all the keyboards you have installed and see which one is causing the keyboard doubling.  There's lots of stuff in https://github.com/gnome-terminator/terminator/pull/674 that should help you troubleshoot this problem.

If you need one of these ibus keyboards and cannot disable it, please open a bug with the ibus project.  There is nothing in Terminator I can do to fix this.

**Comment by mattrose** [comment] 2023-06-18 01:53
I'm going to close this.  This ground is covered in other issues.

**Closed by mattrose** 2023-06-18 01:53 UTC

**Comment by rmarting** [comment] 2023-06-18 16:37
Thanks @mattrose for your comments and references! Yes, I agree closing it. I am digging in about my environment, for now using `ibus exit` for a while to manage multiple terminals is a good enought workaround.

Thanks
