### ISSUE TITLE
Ubuntu 20.04 split terminal broadcast duplicate keys

### ISSUE THREAD

**Issue by ClaudiuPID** [gnome-terminator/terminator#96] opened 2020-05-18 11:44 UTC
If I split a terminal and group it for broadcast I get normal keys sent selected terminal and duplicate keys to the secondary terminal.
I found 2 possible solutions but none of them worked for me:
```
sh -c "GTK_IM_MODULE= setsid terminator"
sh -c "DBUS_SESSION_BUS_ADDRESS='' terminator"
```
Am I the only one experiencing this issue?

**Comment by mattrose** [comment] 2020-05-25 13:54
duplicate of #78

**Closed by mattrose** 2020-05-25 13:54 UTC
