### ISSUE TITLE
Slow or delay activity with terminator on nvidia hardware.

### ISSUE THREAD

**Issue by sjmunizsantex** [gnome-terminator/terminator#912] opened 2024-05-31 17:08 UTC
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.
- Done, issue still present.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue
```
$ cat $HOME/.config/terminator/config
[global_config]
  dbus = False
  handle_size = 10
  extra_styling = False
  inactive_color_offset = 1.0
  enabled_plugins = ,
  suppress_multiple_term_dialog = True
  title_use_system_font = False
  title_font = Sans 12
[keybindings]
  switch_to_tab_1 = <Alt>1
  switch_to_tab_2 = <Alt>2
  switch_to_tab_3 = <Alt>3
  switch_to_tab_4 = <Alt>4
  switch_to_tab_5 = <Alt>6
  switch_to_tab_6 = <Alt>7
  switch_to_tab_10 = <Alt>0
[profiles]
  [[default]]
    cursor_color = "#aaaaaa"
    font = Monospace 16
    scrollback_lines = 20000
    use_system_font = False
    copy_on_selection = True
[layouts]
  [[default]]
    [[[child0]]]
      type = Window
      parent = ""
      order = 0
      position = 74:34
      maximised = False
      fullscreen = False
      size = 1781, 1087
      title = sjmuniz@void: ~
      last_active_term = 34e80ba2-7f7f-4b12-8dc3-cb741cf8cf81
      last_active_window = True
    [[[terminal1]]]
      type = Terminal
      parent = child0
      order = 0
      profile = default
      uuid = 34e80ba2-7f7f-4b12-8dc3-cb741cf8cf81
[plugins]
```
Fill out as many of these fields as you can

**Describe the bug**
While using my discrete nvidia card (GeForce RTX 3070 Mobile) with nvidia module version NVIDIA 535.171.04 terminator is sluggish. This does not happen with the onboard amdgpu card.

Sluggish here means that:
- Sometimes console takes ~200/300 ms to update on any output.
- Scrolling back and forth using shift-pg up/down at some point stalls and does not update until I stop hitting the keyboard.
- completing a path with <tab> sometimes takes 500 ms to offer alternatives. Think like `ls /etc/pro<tab><tab>` freezing, 500 ms later options come up.
- Sometimes typing fast stalls without updating terminal until  ~500/700 ms later, then sometimes the typed text show up, sometimes it is lost.
- All in all, it feels like I am working over ssh to a host with bad connectivity.

**To Reproduce**
Open terminator on an nvidia enabled machine and start typing. The effect is not so noticeable but does exist in the default ubuntu terminal.

**Expected behavior**
I've temporarily switched to kitty, which is responsive and predictable. 

**Screenshots**
I tried to record a video, but it is so subtle that it doesn't really register other than the delay between pressing the keys and the response in the terminal.

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Ubuntu 
 - Version: 22.04.4 LTS
 - Display Technology: X11

**Additional context**
$ apt show terminator
Package: terminator
Version: 2.1.3-1

I installed the PPA version and problem is still there.

The issue seems to be present in: terminator, gnome terminal, tilix. Not present: kitty, xterm.

**Comment by egmontkob** [comment] 2024-05-31 19:12
Dup of #899.

**Comment by egmontkob** [comment] 2024-05-31 19:22
See also https://askubuntu.com/questions/1509058/input-delay-on-terminal-ubuntu-22-04-4.

**Comment by mattrose** [comment] 2024-05-31 21:34
Thanks for this Egmont.  I had forgotten about this one.  Resolving as Dupe of #899

**Closed by mattrose** 2024-05-31 21:34 UTC
