### ISSUE TITLE
terminator -x <command> does not work if there's a Terminator window already open

### ISSUE THREAD

**Issue by TyrasNistru** [gnome-terminator/terminator#739] opened 2023-04-06 20:43 UTC
**Describe the bug**
If there's no Terminator window opened, running `terminator -x <command>` will open a terminator window with `<command>` running. But if there's a Terminator window already open, nothing happens: no new window or tab is opened and no command is run. Same happens when running x-terminal-emulator -e <command> when Terminator is the default terminal application.

**To Reproduce**
- Open a Terminator window
- run something that would issue a `terminator -x <command>`, or run `terminator -x <command>` in the window opened before.

**Expected behavior**
A new Terminator tab or window to open with the specified command running

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu Budgie 22.04.2 LTS X11
 - Terminator 2.1.3

**Comment by nautics889** [comment] 2023-04-17 17:58
Hello, @TyrasNistru 

I couldn't reproduce the behaviour you've encounter on. Having almost same environment.

OS: Ubuntu "Jammy" 22.04.1 LTS on top of WSL
Terminator: v2.1.3

Here what i did (correct me if i'm mistaken):

1. Run terminator at first with command `./terminator &` (`&` is just to start another one from this command line);
2. Run terminator providing `-x` flag, e. g. with command `./terminator -x 'date; sleep 6'`(`sleep` should be supplied for prevent terminal's quiting right after the command is executed);

The terminator's window has opened correctly at the second step and `date` command has been executed (and `date` output was displayed for 6 seconds).

Here is how it looks like:
![terminator_with_x_command](https://user-images.githubusercontent.com/31508183/232570221-806adf7d-9616-40a9-8c95-05261a2e6167.gif)

**Comment by mattrose** [comment] 2023-04-19 12:19
Hmm, this works for me on 2.1.3 as well.  There were some bugs with parsing -e args that may not be fixed in 2.1.3, but -x works as expected.  I have Tilix around too, can you give me an example of a command that works as expected in Tilix but not in terminator?

**Comment by TyrasNistru** [comment] 2023-05-19 14:47
Sorry for taking too long to answer this. Domestic problems.

TBH, on the command line, I can't reproduce it either anymore. But the problem with the QtCreator IDE still persists. I don't know where the problem is anymore.

You can reproduce it (on Ubuntu Jammy at least), by using QtCreator and trying to run a project with the setting "run in terminal" enabled on your project settings. 

If you change in settings below to use tilix instead of x-terminal-emulator, it works as intended.
If you use as it is below, or change it to `terminator` and `-x` respectively, it will happens as I said in the issue description.

![Screenshot from 2023-05-19 10-35-17](https://github.com/gnome-terminator/terminator/assets/9531350/a3fe0fd3-3a73-44eb-bc70-8118865f5535)

**Comment by aplatypus** [comment] 2023-08-31 04:14
I ran across the reported behaviour for this issue using the `remotinator` command to open a tab.   I did a few tests with `terminator` as shown above and the same result; nothing happened as if it didn't work.

While testing with the `remotinator` I discovered that "something" does happen but it appears as if there was not new tab.  Here's what I found:

 1. The commands below were used to test the `--execute` option.
   * `$ terminator -x touch abc`
   * `$ remotinator  vsplit -x "touch xxx"
 2. In both cases the files "abc" and "xyz" were created and the command prompt returned.
 3. What is actually happening is that both command examples create a new terminal session; in a tab for `terminator` and a new split panel for the `vsplit` command.
 4. Then the command executes and finally
 5. The new tab or panel exits!
 6. So the appearance is as if Nothing Happened.

I expect the panel or tab to Remain Open, if it doesn't open a tab/panel why would I use an open tab/panel command?  

If I ever wanted to close the newly opened terminal I could issue an `exit` so closing the tab has no benefit.

Hope this helps this problem to get unravelled/resolved.

**Comment by aplatypus** [comment] 2023-10-07 13:17
Hoping this assists others with objectives similar to mine.  In my case I want to perform something like:

    $  terminator --new-tab  -x 'touch abc; touch XYZ; ls -l'
    $ 
    $ #   OR ... 
    $ 
    $  remotinator new_tab   -x 'touch abc; touch XYZ; ls -l'

... where the "new-tab" remains open as an interactive terminal just as if I'd only issued the appropriate command to open a new tab, either:

    $  remotinator new_tab
or

     $  terminator --new-tab

... having _executed_ the commands from the `--execute` option.

----
I believe that this is a recipe ... Either of these commands work from a shell command line, either:

    $ rm abc XXX; terminator --new-tab -x 'touch abc; touch XXX; ls -l; bash -i'
_or_

    $ rm abc XXX; terminator -x 'touch abc; touch XXX; ls -l; alias; bash -i'

Each version leaves you with a new tab ready to work as if you had pressed `Ctrl/Shift-T`; with the extra advantage of having executed the preface commands in this case: "`touch abc; touch XYZ; ls`".  
* The first pattern opens a new tab in the current `terminator` window.
* The second option creates a tab within a new `terminator` window  initialised by the prefaced commands.

Finally the `bash -i` instruction leaves the new terminal tab open and ready to work, with all the usual `.bashrc` settings and initialisation.  The thing to note here is that the existing `.bashrc` contents can override what ever was done in the sequence of preface commands (_as show herein_).

In the example above I ensure that files: `abc` and `XYZ` have been removed before the new tab command is fired-off.  Teh `ls -l` command is a way to confirm that: (a) both `touch` commands were effective and (b) the new terminal emits `stdout` from said preface commands is displayed on the new tab.  

Much credit for this approach goes to [Peque](https://stackoverflow.com/users/3577054/peque) from Stackoverflow:
* [**Using Python Virtual Environments with Terminator**](https://stackoverflow.com/a/31524868/108350)

In either case you may invoke a custom `initialisation`/`rc` script **but** only if the interactive flag `-i` is passed at the end of the commad pattern works :thumbsup:  :white_check_mark::

    $ rm abc XXX; terminator -x 'touch abc; touch XXX; ls -l; alias; bash --rcfile ./auto.bashrc -i'

... as envisioned.  The following alternative  does not work   :x: :

    $ rm abc XXX; terminator -x 'touch abc; touch XXX; ls -l; alias; bash  -i  --rcfile ./auto.bashrc'

I reckon that can assist people struggling with `terminator v2` and the `--command` or `--execute` options can see the way forward :wink:  Best of luck  :four_leaf_clover:

**Closed** 2023-11-12 15:02 UTC
Labels: question
